backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: /uploads

collections:
- label: "Homepage"
  name: "pages"
  files:
    - label: "Header"
      name: "header"
      file: "content/header.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Description, name: body, widget: markdown}
        - {label: Image, name: image, widget: image}
    - label: "Over ons"
      name: "about"
      file: "content/about.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Description, name: body, widget: markdown}
    - label: "Openingsuren"
      name: "hours"
      file: "content/hours.md"
      fields:
        - {label: Maandag, name: monday, widget: string}
        - {label: Dindsdag, name: tuesday, widget: string}
        - {label: woensdag, name: wednesday, widget: string}
        - {label: Donderdag, name: thursday, widget: string}
        - {label: Vrijdag, name: friday, widget: string}
        - {label: Zaterdag, name: saturday, widget: string}
        - {label: Zondag, name: sunday, widget: string}
- name: 'products'
  label: 'Products'
  label_singular: 'Product'
  folder: 'content/products'
  format: 'frontmatter'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Description', name: 'body', widget: 'markdown' }
    - { label: "On homepage", name: "homepage", widget: "boolean", default: false }
    - { label: "Image", name: "image", widget: "image" }
    - label: "Subproducts"
      name: "subproducts"
      format: 'frontmatter'
      widget: "list"
      fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
      - { label: "Image", name: "image", widget: "image", required: false }
- name: 'promotions'
  label: 'Promotions'
  label_singular: 'Promotion'
  folder: 'content/promotions'
  format: 'frontmatter'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Description', name: 'body', widget: 'markdown' }
    - { label: "Image", name: "image", widget: "image" }
    - { label: "Start time", name: "start", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm" }
    - { label: "End time", name: "end", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm" }